title: I Putu Sukma | CV
description:  I Putu Sukma Hendrawan CV
url: https://git-iputusukma.github.io/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
